import NLAlib.Sketching.CountSketch
import NLAlib.Sketching.CountSketchExpectation
import NLAlib.Sketching.CountSketchMoments
import NLAlib.Sketching.CountSketchTail
import NLAlib.Sketching.FiniteSampling
import NLAlib.Sketching.LeverageSampling
import NLAlib.Sketching.SRHT
import NLAlib.Sketching.SRHTCore
import NLAlib.Sketching.SRHTFlattening
import NLAlib.Sketching.SRHTParameters
import NLAlib.Sketching.SRHTWithReplacement
import NLAlib.Sketching.SamplingMultiplication
import NLAlib.Sketching.SamplingMultiplicationBounds
import NLAlib.Sketching.SparseEmbedding
import NLAlib.Sketching.SparseEmbeddingTransport
import NLAlib.Sketching.SparseFiniteIndex
import NLAlib.Sketching.SparseFock.BandCoefficientBounds
import NLAlib.Sketching.SparseFock.BandEnvelope
import NLAlib.Sketching.SparseFock.BandInventory
import NLAlib.Sketching.SparseFock.ConcreteBandAssembly
import NLAlib.Sketching.SparseFock.ConcreteBandEnvelope
import NLAlib.Sketching.SparseFock.ConcreteLadder
import NLAlib.Sketching.SparseFock.ConcreteLadderIteration
import NLAlib.Sketching.SparseFock.ConcreteMomentEndgame
import NLAlib.Sketching.SparseFock.DirectionalBounds
import NLAlib.Sketching.SparseFock.DirectionalConcrete
import NLAlib.Sketching.SparseFock.DirectionalMarkedCoefficients
import NLAlib.Sketching.SparseFock.DirectionalMarkedReindexing
import NLAlib.Sketching.SparseFock.DirectionalNormalized
import NLAlib.Sketching.SparseFock.DirectionalOccupationEnergy
import NLAlib.Sketching.SparseFock.DirectionalOutputEnergy
import NLAlib.Sketching.SparseFock.DirectionalRestrictedBounds
import NLAlib.Sketching.SparseFock.DirectionalSiteTransitions
import NLAlib.Sketching.SparseFock.DistributionBridges
import NLAlib.Sketching.SparseFock.EmbeddingAssembly
import NLAlib.Sketching.SparseFock.ExactColumnMarginals
import NLAlib.Sketching.SparseFock.ExactConditionalBarycenter
import NLAlib.Sketching.SparseFock.ExactConditionalMatrixTransfer
import NLAlib.Sketching.SparseFock.ExactConditionalSupport
import NLAlib.Sketching.SparseFock.ExactCoordinateSymmetry
import NLAlib.Sketching.SparseFock.ExactIIDMatrixError
import NLAlib.Sketching.SparseFock.ExactMomentTransfer
import NLAlib.Sketching.SparseFock.ExactSelectionSymmetry
import NLAlib.Sketching.SparseFock.ExactSignActions
import NLAlib.Sketching.SparseFock.ExactSparseEmbedding
import NLAlib.Sketching.SparseFock.ExactSparseMatrixEmbedding
import NLAlib.Sketching.SparseFock.ExactSparseMomentMatching
import NLAlib.Sketching.SparseFock.ExactSparseProjectionTail
import NLAlib.Sketching.SparseFock.ExactSparseRoundedBounds
import NLAlib.Sketching.SparseFock.ExternalOperators
import NLAlib.Sketching.SparseFock.FiniteHilbert
import NLAlib.Sketching.SparseFock.FiniteLocalMoments
import NLAlib.Sketching.SparseFock.FiniteSiteOperators
import NLAlib.Sketching.SparseFock.GlobalBands
import NLAlib.Sketching.SparseFock.HeavyAnalysisOperators
import NLAlib.Sketching.SparseFock.HeavyBandsConcrete
import NLAlib.Sketching.SparseFock.HeavyCreationEnergy
import NLAlib.Sketching.SparseFock.HeavyDemotionEnergy
import NLAlib.Sketching.SparseFock.HeavyDiagonalEnergy
import NLAlib.Sketching.SparseFock.HeavyGradeProjections
import NLAlib.Sketching.SparseFock.HeavyLoweringBound
import NLAlib.Sketching.SparseFock.HeavyMarkedSites
import NLAlib.Sketching.SparseFock.HeavyNormalizedBands
import NLAlib.Sketching.SparseFock.HeavyOccupationIdentity
import NLAlib.Sketching.SparseFock.HeavyPreservingBound
import NLAlib.Sketching.SparseFock.HeavyPreservingGram
import NLAlib.Sketching.SparseFock.HeavyRaisingBound
import NLAlib.Sketching.SparseFock.HeavyRowFactorization
import NLAlib.Sketching.SparseFock.IndependentFrameAssembly
import NLAlib.Sketching.SparseFock.LightAnalysisGram
import NLAlib.Sketching.SparseFock.LightBandsConcrete
import NLAlib.Sketching.SparseFock.LightBlockDecomposition
import NLAlib.Sketching.SparseFock.LightCrossContraction
import NLAlib.Sketching.SparseFock.LightCrossCoordinates
import NLAlib.Sketching.SparseFock.LightGradeNorm
import NLAlib.Sketching.SparseFock.LightGramQuadratic
import NLAlib.Sketching.SparseFock.LightHardCoreEmbedding
import NLAlib.Sketching.SparseFock.LightLabelledSlots
import NLAlib.Sketching.SparseFock.LightLegalTransitions
import NLAlib.Sketching.SparseFock.LightMixedFactorization
import NLAlib.Sketching.SparseFock.LightMoveOrbits
import NLAlib.Sketching.SparseFock.LightNormalizedBands
import NLAlib.Sketching.SparseFock.LightOperators
import NLAlib.Sketching.SparseFock.LightOrbitCompression
import NLAlib.Sketching.SparseFock.LightPatternWords
import NLAlib.Sketching.SparseFock.LightPreservingDiagonal
import NLAlib.Sketching.SparseFock.LightRowFactorization
import NLAlib.Sketching.SparseFock.LightSectorAbstract
import NLAlib.Sketching.SparseFock.LightSectorConcrete
import NLAlib.Sketching.SparseFock.LightSynthesisBounds
import NLAlib.Sketching.SparseFock.LightZeroBlock
import NLAlib.Sketching.SparseFock.LocalOperators
import NLAlib.Sketching.SparseFock.MatrixFrameBridge
import NLAlib.Sketching.SparseFock.MatrixTail
import NLAlib.Sketching.SparseFock.MixedBandsConcrete
import NLAlib.Sketching.SparseFock.MixedNormalizedBands
import NLAlib.Sketching.SparseFock.MixedRestrictedBounds
import NLAlib.Sketching.SparseFock.MixedRowFactorization
import NLAlib.Sketching.SparseFock.MomentTransfer
import NLAlib.Sketching.SparseFock.NamedBands
import NLAlib.Sketching.SparseFock.PaperParameters
import NLAlib.Sketching.SparseFock.ParsevalFrame
import NLAlib.Sketching.SparseFock.Pattern
import NLAlib.Sketching.SparseFock.ProductFock
import NLAlib.Sketching.SparseFock.ScalarBounds
import NLAlib.Sketching.SparseFock.SparseEmbedding
import NLAlib.Sketching.SparseFock.SparseFailureOrder
import NLAlib.Sketching.SparseFock.SparseIIDConditionalBarycenter
import NLAlib.Sketching.SparseFock.SparseIIDCoupling
import NLAlib.Sketching.SparseFock.SparseIIDFiniteLaws
import NLAlib.Sketching.SparseFock.SparseIIDSelectionKernel
import NLAlib.Sketching.SparseFock.SparseIIDSelectorMarginals
import NLAlib.Sketching.SparseFock.SparseIIDTransfer
import NLAlib.Sketching.SparseFock.SparseIIDUnconditional
import NLAlib.Sketching.SparseFock.SparseMomentMatching
import NLAlib.Sketching.SparseFock.SparseMomentParameters
import NLAlib.Sketching.SparseFock.SparseParameterConstants
import NLAlib.Sketching.SparseFock.SparseRoundedScales
import NLAlib.Sketching.SparseFock.SparseStackDistribution
import NLAlib.Sketching.SparseFock.SparseStackModel
import NLAlib.Sketching.SparseFock.TernaryJacobi
import NLAlib.Sketching.SparseFock.TracePowerConvexity
import NLAlib.Sketching.SparseFock.TypedBlockCS
import NLAlib.Sketching.SparseFock.UniformExactSBarycenter
import NLAlib.Sketching.SparseFock.UniformExactSCoupling
import NLAlib.Sketching.SparseFock.UniformExactSFiniteLaw
import NLAlib.Sketching.SparseFock.UniformExactSModel
import NLAlib.Sketching.SparseFock.UniformExactSSymmetry
import NLAlib.Sketching.SparseFock.UniformExactSTransfer
import NLAlib.Sketching.SparseFock.VacuumMoment
import NLAlib.Sketching.SparseFrameBridge
import NLAlib.Sketching.SparseLaws
import NLAlib.Sketching.SubGaussianRows
import NLAlib.Sketching.FiniteIndexTransport
import NLAlib.Sketching.Gram
import NLAlib.Sketching.SingularValueEmbedding
import NLAlib.Sketching.Basic
import NLAlib.Sketching.SubspaceEmbedding
import NLAlib.Sketching.JL
import NLAlib.Sketching.SubGaussianJL
import NLAlib.Sketching.Leverage
import NLAlib.Sketching.GaussianEmbedding
import NLAlib.Sketching.ApproxMultiplication

/-!
# Sketching primitives

Layer 3: imports `NLAlib.Matrix`, `NLAlib.Concentration`, `NLAlib.Gaussian`.

Files (atlas ids): `Basic` (`IsSubspaceEmbedding`), `SubspaceEmbedding` (`ose-def`), `JL`
(`jl-distributional`, `jl-lemma`), `Leverage` (`leverage-scores`), `GaussianEmbedding`
(`gaussian-ose`), `ApproxMultiplication` (`amm-ose`).
`SubGaussianJL` proves the independent-entry distributional theorem with an explicit
MGF constant and its independent-isotropic-row extension (`jl-subgaussian`).

Planned: `leverage-sampling-ose`, `amm-sampling`.
-/
