/- Copyright (c) 2026 Diar Heidary.
Ported to NLAlib from commit b9da2b5d96e5fd70252e9c6551aefc92643e7d0b.
Released under the MIT license; see docs/ports/sparse-fock-MIT.txt. -/
import NLAlib.Sketching.SparseFock.SparseIIDFiniteLaws

set_option autoImplicit false

/-!
# Finite support-selection kernel

The true normalized finite support-selection kernel and its joint iid-selector law.
Ported from `SparseFockFormal.SparseIIDCoupling` at commit
b9da2b5d96e5fd70252e9c6551aefc92643e7d0b; supports `sparse-ose`.
-/

open scoped BigOperators InnerProductSpace

namespace NLAlib.SparseFock

namespace SparseIIDCoupling

open ParsevalFrame SparseStackModel SparseStackDistribution

noncomputable section

/-- Whether selector `x` is one of the signed nonzero coordinates of `y`.

Source: ported from `SparseFockFormal.SparseIIDCoupling`,
b9da2b5d96e5fd70252e9c6551aefc92643e7d0b; supports `sparse-ose`. -/
def selectorMatches {b : ℕ} (y : YVector b) (x : SignedHash b) : Prop :=
  y x.1 = outcomeOfSign x.2

/-- Weight of the support-selection kernel `X | Y=y`.

Source: ported from `SparseFockFormal.SparseIIDCoupling`,
b9da2b5d96e5fd70252e9c6551aefc92643e7d0b; supports `sparse-ose`. -/
def kernelWeight {b : ℕ} (hb : 0 < b) (y : YVector b) (x : SignedHash b) : ℝ :=
  by
    classical
    exact if supportSize y = 0 then (selectorLaw b hb).weight x
      else if selectorMatches y x then 1 / (supportSize y : ℝ) else 0

/-- Every support-selection kernel weight is nonnegative.
Source: ported from `SparseFockFormal.SparseIIDCoupling`,
b9da2b5d96e5fd70252e9c6551aefc92643e7d0b; supports `sparse-ose`. -/
theorem kernelWeight_nonneg {b : ℕ} (hb : 0 < b)
    (y : YVector b) (x : SignedHash b) : 0 ≤ kernelWeight hb y x := by
  classical
  by_cases hzero : supportSize y = 0
  · simp [kernelWeight, hzero, (selectorLaw b hb).weight_nonneg x]
  · by_cases hmatch : selectorMatches y x
    · simp [kernelWeight, hzero, hmatch]
    · simp [kernelWeight, hzero, hmatch]

/-- The support-selection kernel weights sum to one for each iid outcome.
Source: ported from `SparseFockFormal.SparseIIDCoupling`,
b9da2b5d96e5fd70252e9c6551aefc92643e7d0b; supports `sparse-ose`. -/
theorem sum_kernelWeight {b : ℕ} (hb : 0 < b) (y : YVector b) :
    ∑ x, kernelWeight hb y x = 1 := by
  classical
  by_cases hzero : supportSize y = 0
  · simp [kernelWeight, hzero, (selectorLaw b hb).sum_weight]
  · rw [Fintype.sum_prod_type]
    simp only [kernelWeight, hzero, ↓reduceIte]
    have sign_univ : (Finset.univ : Finset Sign) = {.plus, .minus} := by
      ext e
      cases e <;> simp
    have hsign (a : Fin b) :
        (∑ e : Sign, if selectorMatches y (a, e)
          then 1 / (supportSize y : ℝ) else 0) =
          if a ∈ support y then 1 / (supportSize y : ℝ) else 0 := by
      cases hya : y a <;>
        simp [sign_univ, selectorMatches, outcomeOfSign, support, hya]
    simp_rw [hsign]
    have hreindex :
        (∑ a, if a ∈ support y then 1 / (supportSize y : ℝ) else 0) =
          ∑ a ∈ support y, 1 / (supportSize y : ℝ) := by
      simpa only [Finset.filter_mem_eq_inter, Finset.univ_inter] using
        (Finset.sum_filter (s := Finset.univ)
          (p := fun a => a ∈ support y)
          (f := fun _ => 1 / (supportSize y : ℝ))).symm
    rw [hreindex]
    have hcard : ((support y).card : ℝ) ≠ 0 := by
      exact_mod_cast (show (support y).card ≠ 0 by simpa [supportSize] using hzero)
    simp only [Finset.sum_const, nsmul_eq_mul, supportSize]
    field_simp

/-- The normalized conditional selector law.

Source: ported from `SparseFockFormal.SparseIIDCoupling`,
b9da2b5d96e5fd70252e9c6551aefc92643e7d0b; supports `sparse-ose`. -/
def selectionKernel {b : ℕ} (hb : 0 < b) (y : YVector b) :
    FiniteLaw (SignedHash b) where
  weight := kernelWeight hb y
  weight_nonneg := kernelWeight_nonneg hb y
  sum_weight := sum_kernelWeight hb y

/-- The finite selection kernel has its defined normalized support weight.
Source: ported from `SparseFockFormal.SparseIIDCoupling`,
b9da2b5d96e5fd70252e9c6551aefc92643e7d0b; supports `sparse-ose`. -/
@[simp] theorem selectionKernel_weight {b : ℕ} (hb : 0 < b)
    (y : YVector b) (x : SignedHash b) :
    (selectionKernel hb y).weight x = kernelWeight hb y x := rfl

/-- One-column joint law generated by first drawing `Y`, then drawing `X|Y`.

Source: ported from `SparseFockFormal.SparseIIDCoupling`,
b9da2b5d96e5fd70252e9c6551aefc92643e7d0b; supports `sparse-ose`. -/
def jointColumnLaw {b : ℕ} (hb : 0 < b) :
    FiniteLaw (YVector b × SignedHash b) where
  weight z := (yVectorLaw b hb).weight z.1 * kernelWeight hb z.1 z.2
  weight_nonneg z := mul_nonneg
    ((yVectorLaw b hb).weight_nonneg z.1) (kernelWeight_nonneg hb z.1 z.2)
  sum_weight := by
    rw [Fintype.sum_prod_type]
    simp_rw [← Finset.mul_sum, sum_kernelWeight hb]
    simpa using (yVectorLaw b hb).sum_weight

end

end SparseIIDCoupling

end NLAlib.SparseFock
